### ISSUE TITLE
crd-extractor.sh does not work properly on CRDs with more than one line matching `kind:`

### ISSUE THREAD

**Issue by ssmall** [datreeio/CRDs-catalog#287]
Any CRD with `metadata.ownerReferences` populated will break the script. E.g.

```yaml
metadata:
  ownerReferences:
    - apiVersion: core.cnrm.cloud.google.com/v1beta1
      kind: ConfigConnector
      name: configconnector.core.cnrm.cloud.google.com
```

causes the script to incorrectly match `kind: ConfigConnector` as the kind for the CRD
