### ISSUE TITLE
Opentelemetry sidecar schema: `managementState` required when it's not

### ISSUE THREAD

**Issue by luispabon** [datreeio/CRDs-catalog#430]
Looks like [certain changes here](https://github.com/datreeio/CRDs-catalog/commit/ddd9802b9428a96727151b55027f5027feb0f575) have broken validation of charts generated by the official opentelemetry chart:

```
# Validation via Kubeconform
Templating release=otel, chart=charts/system/otel

stdin - OpenTelemetryCollector otel-collector-sidecar is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec' does not validate with https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/opentelemetry.io/opentelemetrycollector_v1alpha1.json#/properties/spec/required: missing properties: 'managementState'
```

This is with otel chart 0.74.3 (newest) and the following OpenTelemetryCollector:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-sidecar
spec:
  mode: sidecar

  config: |
    receivers:
      jaeger:
        protocols:
          thrift_compact:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      logging:
      kafka:
        brokers:
          - kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
          - kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092
          - kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092
        topic: {{ .Values.environment }}.jaeger-spans.0
        encoding: jaeger_json
        protocol_version: 2.0.0

    service:
      pipelines:
        traces:
          receivers: [jaeger,otlp]
          processors: [batch]
          exporters: [kafka]
```

The `managementState` property has a default value of `managed`, therefore it is not required:

https://github.com/open-telemetry/opentelemetry-operator/blob/main/config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml#L2316
