### ISSUE TITLE
source.toolkit.fluxcd.io/v1beta2 needs updating

### ISSUE THREAD

**Issue by gilbahat** [datreeio/CRDs-catalog#89]
Hi,

validation fails on the following valid manifest:

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  type: oci
  interval: 30m
  url: oci://public.ecr.aws/karpenter
```

reference: https://fluxcd.io/flux/guides/helmreleases/#helm-oci-repository

validation error:

❌  k8s schema validation error: For field spec: Additional property type is not allowed

please update the relevant CRDs
